Bump up the console text size to 20
ChaosInitiative/p2ce-panorama-ui pull request #10
Opened 2022-07-24 16:05 UTC by ashifolfi

The current font size is a bit hard to read for me. So I bumped it up to make it easier to read.
Feel free to knock it down a few if it's a bit too large.

comparison
![image](https://user-images.githubusercontent.com/29577987/180655977-195e381c-79be-4624-91e4-6a29226c8e2a.png)
![image](https://user-images.githubusercontent.com/29577987/180655973-e5b7f69b-1474-4a60-8bcc-6c7f77bc236e.png)

2022-07-24 16:06 UTC, AWildErin commented
Okay, I see https://github.com/ChaosInitiative/Portal-2-Community-Edition/issues/913 affects new installs too

2022-07-24 16:16 UTC, hexaflexahexagon commented
to me it looks like the font is contributing more to that screenshot being hard to read, maybe we should wait on this until after we get that fixed & back to something monospaced to see if it's still necessary?

2022-07-24 16:18 UTC, AWildErin commented
> to me it looks like the font is contributing more to that screenshot being hard to read, maybe we should wait on this until after we get that fixed & back to something monospaced to see if it's still necessary?

Yeah, I'm not quite sure what's going on with the font, and nobody else who has had the problem (mostly team members) seems to have no idea what's going on either. Bit of a tricky one, since it works for like 95% of people

2022-07-24 16:22 UTC, ashifolfi commented
it might be worthwhile to add some sort of fix or maybe the ability to easily increase console font size without editing the panorama files until you can figure out the font issue

2022-07-24 17:03 UTC, craftablescience commented
im fine with bumping up the font size a bit, even with the correct font its really small for me

2022-07-24 17:34 UTC, craftablescience requested changes
i checked ingame and 20px is MASSIVE, mind if its bumped down to 16?

ill add "console text size" to the pano settings issue on gh as well

2022-07-24 17:34 UTC, craftablescience commented on styles/console.sass
> +		font-size: 20px
```suggestion
		font-size: 16px
```

2022-07-24 17:34 UTC, craftablescience commented on styles/console.sass
> +	font-size: 20px
```suggestion
	font-size: 16px
```

2022-08-01 18:12 UTC, craftablescience approved these changes

2022-08-01 18:13 UTC, merged